service: cart-service
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-offline

provider:
  name: aws
  profile: default
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}

functions:
  main:
    handler: dist/main.handler
    timeout: 10
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
