service: import-products-service
frameworkVersion: '3'

package:
  patterns:
    - '../node_modules/**'
    - '!../node_modules/prettier'

provider:
  name: aws
  profile: default
  runtime: nodejs16.x
  region: eu-west-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource: arn:aws:s3:::import-product-service-bucket
    - Effect: Allow
      Action: s3:*
      Resource: arn:aws:s3:::import-product-service-bucket/*

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
          authorizer:
            name: basicAuthorizer
            arn: "arn:aws:lambda:${aws:region}:${aws:accountId}:function:backend-authorization-service-dev-basicAuthorizer"
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: token
    environment:
      S3_BUCKET: import-product-service-bucket
      UPLOADED_DIR: uploaded
      PARSED_DIR: parsed

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: import-product-service-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
    environment:
      S3_BUCKET: import-product-service-bucket
      UPLOADED_DIR: uploaded
      PARSED_DIR: parsed
